apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Kubernetes en Zededa</title>
    </head>
    <body>
        <h1>Kubernetes en Zededa Ok!</h1>
    </body>
    </html>
